In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_excel(r"C:\Users\User\Downloads\test_label_encoder.xlsx")
df

  Weather TimeOfWeek TimeOfDay TrafficJam
0   Clear    Workday   Morning        Yes
1   Clear    Workday   Evening        Yes
2   Clear    Weekend     Lunch         No
3   Rainy    Workday   Morning        Yes
4   Rainy    Workday     Lunch        Yes
5   Rainy    Workday   Evening        Yes
6   Rainy    Weekend     Lunch         No
7   Snowy    Workday   Morning        Yes
8   Snowy    Workday   Evening        Yes
9   Snowy    Weekend     Lunch         No

In [3]:
cols_to_encode = df.columns.tolist()
print(cols_to_encode)

['Weather', 'TimeOfWeek', 'TimeOfDay', 'TrafficJam']

In [5]:
encoders = {}
for col in cols_to_encode:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le 

df

   Weather  TimeOfWeek  TimeOfDay  TrafficJam
0        0           1          2           1
1        0           1          0           1
2        0           0          1           0
3        1           1          2           1
4        1           1          1           1
5        1           1          0           1
6        1           0          1           0
7        2           1          2           1
8        2           1          0           1
9        2           0          1           0

In [7]:
df.to_csv("labelencoder.csv")

In [15]:
# inv = encoder.inverse_transform()

inv = {}

for col in cols_to_encode:
    le = LabelEncoder()
    df[col] = le.fit(df[col])
    df[col] = le.inverse_transform(df[col])

df

IndentationError: unexpected indent (2460930221.py, line 8)